title: <p align="center"> HemanthKumar GK </p>
logo: /assets/img/Hemanth-GK.jpeg

description:
  <p align="center">
  <a href="https://github.com/GK-TechWorld/portpolio/blob/master/docs/Hemanth_CV.pdf">Resume</a> |
  <a href="www.linkedin.com/in/hemanth-kumar-g-k-b8b0ba67">LinkedIn</a> |
  <a href="https://github.com/GK-TechWorld">GitHub</a>
  
  <br>   
  Senior Software Engineer with an experience of 10+ years in embedded
  software development with good understanding of C and C++ programming,
  Linux internals, threads, inter-process communications, deadlocks,
  concurrency control and RTOS concepts with exposure to the complete Software Development Life Cycle.
  <br>
  </p>



theme: jekyll-theme-minimal
